version: "3.9"

services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: "python manage.py runserver 0:${DJANGO_PORT?8000}"
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:${DJANGO_PORT?8000}"
    