# Generated by Django 3.2.13 on 2022-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("unique_hash", models.TextField(max_length=20, unique=True)),
                ("tx_hash", models.TextField(unique=True)),
                ("media_url", models.URLField()),
                ("owner", models.TextField()),
            ],
        ),
    ]
